### ISSUE TITLE
rados/striper test suite is flaky on octopus

### ISSUE THREAD

**Issue by phlogistonjohn** [ceph/go-ceph#1020]
Example: https://github.com/ceph/go-ceph/actions/runs/10413135499/job/28840033245

The new rados/striper package appears to occasionally panic when the test suite is run with the ceph octopus job.
Over the past week it has failed 2 or 3 times.

Given that this only appears to occur on octopus and octopus is next on this to lose support in the go-ceph test matrix I'm considering just disabling rados/striper on octopus preemptively. But I haven't made up my mind yet and I am open to suggestions.

**Comment by anoopcs9** [comment]
> Example: https://github.com/ceph/go-ceph/actions/runs/10413135499/job/28840033245
```
=== RUN   TestStriperTestSuite
=== RUN   TestStriperTestSuite/TestListXattrs
=== RUN   TestStriperTestSuite/TestNewStriper
=== RUN   TestStriperTestSuite/TestNewStriperWithLayout
=== RUN   TestStriperTestSuite/TestReadAppend
coverage: 63.8% of statements in github.com/ceph/go-ceph/rados/striper
panic: test timed out after 10m0s
	running tests:
		TestStriperTestSuite (10m0s)
		TestStriperTestSuite/TestReadAppend (9m59s)
. . .
goroutine 24 [syscall]:
github.com/ceph/go-ceph/rados._Cfunc_rados_shutdown(0x7f32540134c0)
	_cgo_gotypes.go:1606 +0x3f
github.com/ceph/go-ceph/rados.freeConn.func1(0xc000141c90?)
	/go/src/github.com/ceph/go-ceph/rados/rados.go:126 +0x34
github.com/ceph/go-ceph/rados.freeConn(0xc000204b00)
	/go/src/github.com/ceph/go-ceph/rados/rados.go:126 +0x45
github.com/ceph/go-ceph/rados.(*Conn).Shutdown(...)
	/go/src/github.com/ceph/go-ceph/rados/conn.go:77
github.com/ceph/go-ceph/rados/striper.(*StriperTestSuite).TearDownTest(0xc000072240)
	/go/src/github.com/ceph/go-ceph/rados/striper/striper_test.go:70 +0x35
github.com/stretchr/testify/suite.Run.func1.1()
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:184 +0x269
github.com/stretchr/testify/suite.Run.func1(0xc0002404e0)
	/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:203 +0x498
testing.tRunner(0xc0002404e0, 0xc0002001b0)
	/opt/go/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 7
	/opt/go/src/testing/testing.go:1743 +0x390
FAIL	github.com/ceph/go-ceph/rados/striper	600.108s
```

I see _TearDownTest_ in the backtrace. At least this one most likely timed out.

I couldn't find any other occurrence(post merge) where it points at a real failure.

**Comment by anoopcs9** [comment]
CI runs are stable enough these days. Please reopen in case it fails more consistently.
