### ISSUE TITLE
Fatal error appears when SetOmap is called

### ISSUE THREAD

**Issue by RobotHuang** [ceph/go-ceph#489]
I call `SetOmap` like below:
```go
func (r *Rados) SetOmap(pool string, oid string, pairs map[string][]byte) error {
	ioctx, err := r.Conn.OpenIOContext(pool)
	if err != nil {
		return err
	}
	defer ioctx.Destroy()
	err = ioctx.SetOmap(oid, pairs)
	return err
}
```
When I call `SetOmap`, it shows:
```
fatal error: runtime.SetFinalizer: cannot pass *        github.x2ecom..z2fceph..z2fgo..z2dceph..z2frados        rados.setOmapStep to finalizer func(    github.x2ecom..z2fceph..z2fgo..z2dceph..z2frados  rados.opStep)

goroutine 1 [running]:
runtime.dopanic_m
        ../../../libgo/go/runtime/panic.go:1208
runtime.fatalthrow
        ../../../libgo/go/runtime/panic.go:1071
runtime.throw
        ../../../libgo/go/runtime/panic.go:1042
runtime.SetFinalizer
        ../../../libgo/go/runtime/mfinal.go:367
rados.newSetOmapStep
        /root/go/pkg/mod/github.com/ceph/go-ceph@v0.8.0/rados/omap.go:77
github.x2ecom..z2fceph..z2fgo..z2dceph..z2frados.WriteOp.SetOmap
        /root/go/pkg/mod/github.com/ceph/go-ceph@v0.8.0/rados/write_op.go:94
github.x2ecom..z2fceph..z2fgo..z2dceph..z2frados.IOContext.SetOmap
        /root/go/pkg/mod/github.com/ceph/go-ceph@v0.8.0/rados/omap.go:226
octopus..z2fconnection.Rados.SetOmap
        /root/go/src/octopus/connection/ceph.go:197
main.main
        /root/go/src/octopus/main.go:19
runtime.main
        ../../../libgo/go/runtime/proc.go:235
exit status 2
```
ceph version: nautilus

**Comment by phlogistonjohn** [comment]
Thanks for the report. That certainly does not look like intended behavior.

What Go (golang) version are you using?

If you are able and willing to patch your local copy of go-ceph, can you try applying the following patch and reporting if the behavior changes?

```
diff --git a/rados/omap.go b/rados/omap.go
index 79b4c8e..4d530ea 100644
--- a/rados/omap.go
+++ b/rados/omap.go
@@ -74,7 +74,7 @@ func newSetOmapStep(pairs map[string][]byte) *setOmapStep {
                i++
        }
 
-       runtime.SetFinalizer(sos, opStepFinalizer)
+       runtime.SetFinalizer(sos, (*setOmapStep).free)
        return sos
 }

```

**Comment by RobotHuang** [comment]
This is my go version: `go version go1.14.2 gccgo (GCC) 10.1.0 linux/amd64`
I will try to do it, thanks.

**Comment by RobotHuang** [comment]
I find that it is a problem about go version. When I use `go1.16.2 linux/amd64`, it could run successfully.

**Comment by phlogistonjohn** [comment]
Ah, thanks for looking into that. We have not tested with gccgo, and do not have plans to support it at the moment. If you can stick with Go's default compiler (gc) and supported versions of Go, may we close this issue?
Thanks!

**Comment by RobotHuang** [comment]
Yeah, thanks a lot.
