### ISSUE TITLE
rados: MonCommand exec "fs authorize" panic

### ISSUE THREAD

**Issue by elrondwong** [ceph/go-ceph#567]
|Component|version|
|:--:|:--:|
|go ceph|v0.11.0|
|ceph|14.2.21|

exec command `ceph fs authorize cephfs client.user1 /test rw`
- **conn.MonCommand** - **panic** 
- **shell** - **completed** 
- **c++ API** - **completed**

panic code:

```go
   conn, err := radosConn()
    command, _ := json.Marshal(map[string]interface{}{
        "prefix": "fs authorize",
        "format": "json",
        "entity": "client.user1",
        "filesystem": "cephfs",
        "caps": []string{"/test", "rw"},
    })
   buf, info, err := conn.MonCommand(command)
```

panic

```log
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb50 pc=0x7f831a7a9d00]

runtime stack:
runtime.throw(0x5156f5, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x288

goroutine 1 [syscall]:
runtime.cgocall(0x4e3769, 0xc00019d930, 0x4ecca0)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc00019d8d0 sp=0xc00019d898 pc=0x4085bb
github.com/ceph/go-ceph/rados._Cfunc_rados_mon_command(0x0, 0xc0001ba080, 0x1, 0x0, 0x0, 0xc000196398, 0xc0001963a0, 0xc0001963a8, 0xc0001963b0, 0x0)
	_cgo_gotypes.go:849 +0x4b fp=0xc00019d930 sp=0xc00019d8d0 pc=0x4e03ab
github.com/ceph/go-ceph/rados.(*Conn).MonCommandWithInputBuffer.func1(0xc0001922a0, 0xc000196360, 0xc000196390, 0x0)
	/root/go/pkg/mod/github.com/ceph/go-ceph@v0.11.0/rados/command.go:39 +0x296 fp=0xc00019da10 sp=0xc00019d930 pc=0x4e14b6
github.com/ceph/go-ceph/rados.(*Conn).MonCommandWithInputBuffer(0xc0001922a0, 0xc0001d0000, 0x6e, 0x70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/ceph/go-ceph@v0.11.0/rados/command.go:39 +0x20a fp=0xc00019dbf0 sp=0xc00019da10 pc=0x4e0a0a
github.com/ceph/go-ceph/rados.(*Conn).MonCommand(0xc0001922a0, 0xc0001d0000, 0x6e, 0x70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/ceph/go-ceph@v0.11.0/rados/command.go:20 +0xcf fp=0xc00019dce0 sp=0xc00019dbf0 pc=0x4e06af
main.CreateFSAuth(0x0, 0x0)
```

**Comment by phlogistonjohn** [comment]
Hi, thanks for the report.

I'm not sure if this is only in your example code or not, but you're not checking the result from `radosConn` which could possibly lead to an invalid `conn` being used. The backtrace could be indicating that `conn.cluster` is nil.

Alternatively the issue could lie with our command output type. If checking that radosConn returns a valid conn doesn't help could you try applying a patch to go-ceph such as:

```diff
diff --git a/rados/command.go b/rados/command.go
index 7404d31..4e6b90b 100644
--- a/rados/command.go
+++ b/rados/command.go
@@ -6,6 +6,7 @@ package rados
 import "C"

 import (
+       "fmt"
        "unsafe"

        "github.com/ceph/go-ceph/internal/cutil"
@@ -27,6 +28,17 @@ func (c *Conn) MonCommandWithInputBuffer(args, inputBuffer []byte) ([]byte, stri
        co := cutil.NewCommandOutput().SetFreeFunc(radosBufferFree)
        defer co.Free()

+       fmt.Printf(
+               "DEBUG: (%v, %v, %v, %v, %v, %v, %v, %v, %v)",
+               c.cluster,
+               (**C.char)(ci.Cmd()),
+               C.size_t(ci.CmdLen()),
+               (*C.char)(ci.InBuf()),
+               C.size_t(ci.InBufLen()),
+               (**C.char)(co.OutBuf()),
+               (*C.size_t)(co.OutBufLen()),
+               (**C.char)(co.Outs()),
+               (*C.size_t)(co.OutsLen()))
        ret := C.rados_mon_command(
                c.cluster,
                (**C.char)(ci.Cmd()),
```

I frequently have trouble interpreting the go backtraces and so a debug print like this could help us better determine what isn't right. Thanks!

**Comment by elrondwong** [comment]
Thanks for your reply.

after patch log:

```log
DEBUG: (<nil>, 0xc000010090, 1, <nil>, 0, 0xc000076398, 0xc0000763a0, 0xc0000763a8, 0xc0000763b0)
```
`cluster` is `nil`

In this case, i have create `conn` but i have't call `conn.Connect`, cause `cluster` is `nil`, the following code is called completed.

>  some error handle is ommited
 
```go
    conn, err := rados.NewConn()

    if err != nil {
        fmt.Printf("Error creating connection %s", err)
        return err
    }
    defer conn.Shutdown()
    _ = conn.ReadDefaultConfigFile()
    _ = conn.Connect()
        command, _ := json.Marshal(map[string]interface{}{
        "prefix": "fs authorize",
        "format": "json",
        "entity": "client.user1",
        "filesystem": "cephfs",
        "caps": []string{"/test", "rw"},
    })
     buf, info, err := conn.MonCommand(command)
    if err != nil {
        fmt.Println("mon command exec err: " + err.Error())
        return err
    }
    fmt.Println("buf: " , string(buf))
    fmt.Println("info: ", info)
```

Apologize for my careless.
Thank you!
